apiVersion: v2
name: hcloud-operator
description: Hetzner Kubernetes Infrastructure Controller — ACK-style CRDs for Hetzner Cloud
type: application
version: 0.8.4
appVersion: "0.8.4"
kubeVersion: ">=1.25.0-0"
home: https://github.com/armanfeyzi/hcloud-operator
sources:
  - https://github.com/armanfeyzi/hcloud-operator
keywords:
  - hetzner
  - hcloud
  - operator
  - gitops
maintainers:
  - name: armanfeyzi
    url: https://github.com/armanfeyzi
