apiVersion: infra.hkc.io/v1alpha1
kind: HCloudServer
metadata:
  name: dev-node-1
spec:
  serverType: cx23
  image: ubuntu-22.04
  location: fsn1
  labels:
    env: dev
    managed-by: hcloud-operator
  # sshKeys:
  #   - my-ssh-key
  
