apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- bases/infra.hkc.io_hcloudfirewalls.yaml
- bases/infra.hkc.io_hcloudfloatingips.yaml
- bases/infra.hkc.io_hcloudloadbalancers.yaml
- bases/infra.hkc.io_hcloudnetworks.yaml
- bases/infra.hkc.io_hcloudplacementgroups.yaml
- bases/infra.hkc.io_hcloudprimaryips.yaml
- bases/infra.hkc.io_hcloudservers.yaml
- bases/infra.hkc.io_hcloudvolumes.yaml
